export const NEXT_BALL = 'NEXT_BALL';
export const GOTO_GAME_DETAILS_PAGE='GOTO_GAME_DETAILS_PAGE';
export const SELECT_BATSMAN = 'SELECT_BATSMAN'
export const SELECT_RUNS_SCORED = ' SELECT_RUNS_SCORED'
